# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogpage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='comments',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
