# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-22 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170422_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='rich_content',
            new_name='body',
        ),
    ]
