# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-22 11:38
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170422_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'blockquote', wagtail.wagtailcore.blocks.BlockQuoteBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'raw_html', wagtail.wagtailcore.blocks.RawHTMLBlock()), (b'rich_text', wagtail.wagtailcore.blocks.RichTextBlock())], blank=True, null=True),
        ),
    ]
