# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-22 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170422_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_post',
            field=models.BooleanField(default=False),
        ),
    ]
