# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-22 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_is_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_post',
            field=models.BooleanField(default=True),
        ),
    ]
