# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='intro',
        ),
    ]
