# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-22 11:13
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_rich_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='body',
        ),
        migrations.AlterField(
            model_name='article',
            name='rich_content',
            field=wagtail.wagtailcore.fields.StreamField([(b'blockquote', wagtail.wagtailcore.blocks.BlockQuoteBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock())], blank=True, null=True),
        ),
    ]
